### ISSUE TITLE
Bitte lassen Sie uns die Folien Ihrer Präsentation zukommen

### ISSUE THREAD

**Issue by malvela** [GrainTrackerApp/BatchProcesses-AutomaticProductFeaturesCollection#37]

**Comment by ghost** [comment]
https://seafile.zfn.uni-bremen.de/f/970934484e8a485e8205/
Der Seafile Downloadlink zu den Folien der Präsentation ist auch im Repository im Ordner "Präsentation" in der readme.md zu finden.

**Comment by malvela** [comment]
Vielen Dank!
